import React from 'react';
import { Ionicons } from '@expo/vector-icons';
import { StyleProp, TextStyle } from 'react-native';

interface SafeIoniconsProps {
  name: any; // Accept any type to handle potential objects
  size?: number;
  color?: string;
  style?: StyleProp<TextStyle>;
}

/**
 * Safe wrapper for Ionicons that prevents "[object Object]" errors
 * by validating icon names and providing fallbacks
 */
export function SafeIonicons({ name, size = 24, color = '#000', style }: SafeIoniconsProps) {
  // Convert name to string and validate
  let iconName: string;
  
  if (typeof name === 'string') {
    iconName = name;
  } else if (typeof name === 'object' && name !== null) {
    // Handle object cases - try to extract a string value
    if (name.name && typeof name.name === 'string') {
      iconName = name.name;
    } else if (name.iconName && typeof name.iconName === 'string') {
      iconName = name.iconName;
    } else if (name.icon && typeof name.icon === 'string') {
      iconName = name.icon;
    } else {
      console.warn('SafeIonicons: Received object instead of string for icon name:', name);
      iconName = 'help-circle-outline'; // Fallback icon
    }
  } else {
    console.warn('SafeIonicons: Invalid icon name type:', typeof name, name);
    iconName = 'help-circle-outline'; // Fallback icon
  }

  // Validate that the icon name is a valid Ionicons name
  // Common Ionicons names for fallback
  const validIcons = [
    'home', 'home-outline',
    'person', 'person-outline',
    'settings', 'settings-outline',
    'search', 'search-outline',
    'add', 'add-outline',
    'close', 'close-outline',
    'menu', 'menu-outline',
    'arrow-forward', 'arrow-forward-outline',
    'arrow-back', 'arrow-back-outline',
    'chevron-forward', 'chevron-forward-outline',
    'chevron-back', 'chevron-back-outline',
    'trash', 'trash-outline',
    'edit', 'edit-outline',
    'save', 'save-outline',
    'download', 'download-outline',
    'share', 'share-outline',
    'help-circle', 'help-circle-outline',
    'information-circle', 'information-circle-outline',
    'warning', 'warning-outline',
    'checkmark', 'checkmark-outline',
    'mic', 'mic-outline',
    'stop', 'stop-outline',
    'play', 'play-outline',
    'pause', 'pause-outline',
    'document', 'document-outline',
    'folder', 'folder-outline',
    'calendar', 'calendar-outline',
    'time', 'time-outline',
    'location', 'location-outline',
    'mail', 'mail-outline',
    'call', 'call-outline',
    'camera', 'camera-outline',
    'image', 'image-outline',
    'lock-closed', 'lock-closed-outline',
    'lock-open', 'lock-open-outline',
    'eye', 'eye-outline',
    'eye-off', 'eye-off-outline',
    'heart', 'heart-outline',
    'star', 'star-outline',
    'bookmark', 'bookmark-outline',
    'flag', 'flag-outline',
    'refresh', 'refresh-outline',
    'sync', 'sync-outline',
    'cloud', 'cloud-outline',
    'wifi', 'wifi-outline',
    'bluetooth', 'bluetooth-outline',
    'battery-full', 'battery-full-outline',
    'notifications', 'notifications-outline',
    'notifications-off', 'notifications-off-outline',
    'volume-high', 'volume-high-outline',
    'volume-low', 'volume-low-outline',
    'volume-mute', 'volume-mute-outline',
    'musical-notes', 'musical-notes-outline',
    'headset', 'headset-outline',
    'radio', 'radio-outline',
    'tv', 'tv-outline',
    'desktop', 'desktop-outline',
    'laptop', 'laptop-outline',
    'tablet-portrait', 'tablet-portrait-outline',
    'phone-portrait', 'phone-portrait-outline',
    'watch', 'watch-outline',
    'car', 'car-outline',
    'bus', 'bus-outline',
    'train', 'train-outline',
    'airplane', 'airplane-outline',
    'boat', 'boat-outline',
    'bicycle', 'bicycle-outline',
    'walk', 'walk-outline',
    'fitness', 'fitness-outline',
    'barbell', 'barbell-outline',
    'basketball', 'basketball-outline',
    'football', 'football-outline',
    'golf', 'golf-outline',
    'tennisball', 'tennisball-outline',
    'american-football', 'american-football-outline',
    'baseball', 'baseball-outline',
    'fish', 'fish-outline',
    'flower', 'flower-outline',
    'leaf', 'leaf-outline',
    'sunny', 'sunny-outline',
    'moon', 'moon-outline',
    'partly-sunny', 'partly-sunny-outline',
    'cloudy', 'cloudy-outline',
    'rainy', 'rainy-outline',
    'snow', 'snow-outline',
    'thunderstorm', 'thunderstorm-outline',
    'flash', 'flash-outline',
    'flash-off', 'flash-off-outline',
    'umbrella', 'umbrella-outline',
    'thermometer', 'thermometer-outline',
    'water', 'water-outline',
    'flame', 'flame-outline',
    'earth', 'earth-outline',
    'globe', 'globe-outline',
    'map', 'map-outline',
    'navigate', 'navigate-outline',
    'compass', 'compass-outline',
    'telescope', 'telescope-outline',
    'binoculars', 'binoculars-outline',
    'glasses', 'glasses-outline',
    'eyedrop', 'eyedrop-outline',
    'color-palette', 'color-palette-outline',
    'brush', 'brush-outline',
    'pencil', 'pencil-outline',
    'create', 'create-outline',
    'cut', 'cut-outline',
    'copy', 'copy-outline',
    'duplicate', 'duplicate-outline',
    'clipboard', 'clipboard-outline',
    'attach', 'attach-outline',
    'link', 'link-outline',
    'unlink', 'unlink-outline',
    'code', 'code-outline',
    'code-slash', 'code-slash-outline',
    'terminal', 'terminal-outline',
    'bug', 'bug-outline',
    'construct', 'construct-outline',
    'hammer', 'hammer-outline',
    'build', 'build-outline',
    'cog', 'cog-outline',
    'options', 'options-outline',
    'filter', 'filter-outline',
    'funnel', 'funnel-outline',
    'list', 'list-outline',
    'grid', 'grid-outline',
    'apps', 'apps-outline',
    'layers', 'layers-outline',
    'library', 'library-outline',
    'albums', 'albums-outline',
    'archive', 'archive-outline',
    'filing', 'filing-outline',
    'folder-open', 'folder-open-outline',
    'receipt', 'receipt-outline',
    'newspaper', 'newspaper-outline',
    'book', 'book-outline',
    'journal', 'journal-outline',
    'reader', 'reader-outline',
    'school', 'school-outline',
    'library', 'library-outline',
    'calculator', 'calculator-outline',
    'keypad', 'keypad-outline',
    'card', 'card-outline',
    'wallet', 'wallet-outline',
    'cash', 'cash-outline',
    'logo-bitcoin', 'logo-bitcoin',
    'logo-euro', 'logo-euro',
    'logo-usd', 'logo-usd',
    'pricetag', 'pricetag-outline',
    'pricetags', 'pricetags-outline',
    'storefront', 'storefront-outline',
    'bag', 'bag-outline',
    'basket', 'basket-outline',
    'cart', 'cart-outline',
    'gift', 'gift-outline',
    'ribbon', 'ribbon-outline',
    'trophy', 'trophy-outline',
    'medal', 'medal-outline',
    'rosette', 'rosette-outline',
    'shield', 'shield-outline',
    'shield-checkmark', 'shield-checkmark-outline',
    'shield-half', 'shield-half-outline',
    'key', 'key-outline',
    'finger-print', 'finger-print-outline',
    'scan', 'scan-outline',
    'qr-code', 'qr-code-outline',
    'barcode', 'barcode-outline',
    'id-card', 'id-card-outline',
    'person-add', 'person-add-outline',
    'person-remove', 'person-remove-outline',
    'people', 'people-outline',
    'people-circle', 'people-circle-outline',
    'body', 'body-outline',
    'accessibility', 'accessibility-outline',
    'medical', 'medical-outline',
    'fitness', 'fitness-outline',
    'pulse', 'pulse-outline',
    'heart-half', 'heart-half-outline',
    'heart-dislike', 'heart-dislike-outline',
    'happy', 'happy-outline',
    'sad', 'sad-outline',
    'chatbubble', 'chatbubble-outline',
    'chatbubbles', 'chatbubbles-outline',
    'chatbox', 'chatbox-outline',
    'send', 'send-outline',
    'paper-plane', 'paper-plane-outline',
    'megaphone', 'megaphone-outline',
    'bullhorn', 'bullhorn-outline',
    'radio-button-on', 'radio-button-on-outline',
    'radio-button-off', 'radio-button-off-outline',
    'checkbox', 'checkbox-outline',
    'checkbox-outline', 'checkbox',
    'square', 'square-outline',
    'triangle', 'triangle-outline',
    'ellipse', 'ellipse-outline',
    'diamond', 'diamond-outline',
    'hexagon', 'hexagon-outline',
    'star-half', 'star-half-outline',
    'star-outline', 'star',
    'heart-circle', 'heart-circle-outline',
    'infinite', 'infinite-outline',
    'hourglass', 'hourglass-outline',
    'stopwatch', 'stopwatch-outline',
    'timer', 'timer-outline',
    'alarm', 'alarm-outline',
    'today', 'today-outline',
    'calendar-clear', 'calendar-clear-outline',
    'calendar-number', 'calendar-number-outline',
    'repeat', 'repeat-outline',
    'shuffle', 'shuffle-outline',
    'reorder-two', 'reorder-two-outline',
    'reorder-three', 'reorder-three-outline',
    'reorder-four', 'reorder-four-outline',
    'resize', 'resize-outline',
    'expand', 'expand-outline',
    'contract', 'contract-outline',
    'move', 'move-outline',
    'swap-horizontal', 'swap-horizontal-outline',
    'swap-vertical', 'swap-vertical-outline',
    'return-up-back', 'return-up-back-outline',
    'return-up-forward', 'return-up-forward-outline',
    'return-down-back', 'return-down-back-outline',
    'return-down-forward', 'return-down-forward-outline',
    'undo', 'undo-outline',
    'redo', 'redo-outline',
    'reload', 'reload-outline',
    'refresh-circle', 'refresh-circle-outline',
    'sync-circle', 'sync-circle-outline',
    'download-outline', 'download',
    'cloud-download', 'cloud-download-outline',
    'cloud-upload', 'cloud-upload-outline',
    'cloud-done', 'cloud-done-outline',
    'cloud-offline', 'cloud-offline-outline',
    'server', 'server-outline',
    'hardware-chip', 'hardware-chip-outline',
    'cellular', 'cellular-outline',
    'wifi-outline', 'wifi',
    'bluetooth-outline', 'bluetooth',
    'power', 'power-outline',
    'battery-charging', 'battery-charging-outline',
    'battery-dead', 'battery-dead-outline',
    'battery-half', 'battery-half-outline',
    'flashlight', 'flashlight-outline',
    'bulb', 'bulb-outline',
    'sunny-outline', 'sunny',
    'moon-outline', 'moon',
    'contrast', 'contrast-outline',
    'invert-mode', 'invert-mode-outline',
    'color-fill', 'color-fill-outline',
    'color-filter', 'color-filter-outline',
    'color-wand', 'color-wand-outline',
    'eyedrop-outline', 'eyedrop',
    'image-outline', 'image',
    'images', 'images-outline',
    'camera-outline', 'camera',
    'camera-reverse', 'camera-reverse-outline',
    'videocam', 'videocam-outline',
    'videocam-off', 'videocam-off-outline',
    'film', 'film-outline',
    'play-back', 'play-back-outline',
    'play-forward', 'play-forward-outline',
    'play-skip-back', 'play-skip-back-outline',
    'play-skip-forward', 'play-skip-forward-outline',
    'pause-outline', 'pause',
    'stop-outline', 'stop',
    'record', 'record-outline',
    'recording', 'recording-outline',
    'mic-outline', 'mic',
    'mic-off', 'mic-off-outline',
    'volume-off', 'volume-off-outline',
    'volume-mute-outline', 'volume-mute',
    'headset-outline', 'headset',
    'ear', 'ear-outline',
    'musical-note', 'musical-note-outline',
    'musical-notes-outline', 'musical-notes',
    'radio-outline', 'radio',
    'disc', 'disc-outline',
    'albums-outline', 'albums',
    'library-outline', 'library',
    'tv-outline', 'tv',
    'desktop-outline', 'desktop',
    'laptop-outline', 'laptop',
    'tablet-landscape', 'tablet-landscape-outline',
    'tablet-portrait-outline', 'tablet-portrait',
    'phone-landscape', 'phone-landscape-outline',
    'phone-portrait-outline', 'phone-portrait',
    'watch-outline', 'watch',
    'game-controller', 'game-controller-outline',
    'logo-playstation', 'logo-playstation',
    'logo-xbox', 'logo-xbox',
    'logo-nintendo-switch', 'logo-nintendo-switch',
    'logo-steam', 'logo-steam',
    'dice', 'dice-outline',
    'extension-puzzle', 'extension-puzzle-outline',
    'rocket', 'rocket-outline',
    'planet', 'planet-outline',
    'telescope-outline', 'telescope',
    'magnet', 'magnet-outline',
    'flask', 'flask-outline',
    'beaker', 'beaker-outline',
    'nuclear', 'nuclear-outline',
    'skull', 'skull-outline',
    'warning-outline', 'warning',
    'alert', 'alert-outline',
    'alert-circle', 'alert-circle-outline',
    'information', 'information-outline',
    'information-circle-outline', 'information-circle',
    'help', 'help-outline',
    'help-buoy', 'help-buoy-outline',
    'help-circle-outline', 'help-circle',
    'chatbubble-ellipses', 'chatbubble-ellipses-outline',
    'ellipsis-horizontal', 'ellipsis-horizontal-outline',
    'ellipsis-vertical', 'ellipsis-vertical-outline',
    'more', 'more-outline',
    'add-circle', 'add-circle-outline',
    'remove', 'remove-outline',
    'remove-circle', 'remove-circle-outline',
    'close-circle', 'close-circle-outline',
    'checkmark-circle', 'checkmark-circle-outline',
    'checkmark-done', 'checkmark-done-outline',
    'checkmark-done-circle', 'checkmark-done-circle-outline',
    'radio-button-on-outline', 'radio-button-on',
    'radio-button-off-outline', 'radio-button-off'
  ];

  // If the icon name is not in our known valid list, use a fallback
  if (!validIcons.includes(iconName)) {
    console.warn(`SafeIonicons: Unknown icon name "${iconName}". Using fallback icon.`);
    iconName = 'help-circle-outline';
  }

  try {
    return (
      <Ionicons 
        name={iconName as any} 
        size={size} 
        color={color} 
        style={style} 
      />
    );
  } catch (error) {
    console.error('SafeIonicons: Error rendering icon:', error);
    return (
      <Ionicons 
        name="help-circle-outline" 
        size={size} 
        color={color} 
        style={style} 
      />
    );
  }
}

export default SafeIonicons;
